<?php
/*
 * 	example.php
 * 	Example for requesr lib, a simple PHP request/inclusion system
 *  Copyright (c) 2015 Russell Peterson & Daniel Evans - helical.io
 */
 
require("../lib/requestr.php");

// Create the page using requesr
//		First value is the GET param, this will be used as the class name too
//		Second value is the GET param which will be used for the function we want to run
//		Third value is the folder where your included pages are

// If your url is ?action=home&subaction=news then you need to have:
//	- home.php in /pages/home
//	- 'namespace helical\requestr\page;' in home.php
//  - class home in home.php
//	- function news() in class home

// By default, if no querystring is provided, requestr will try to load /pages/homepage/homepage.php, class homepage function _default()

$requestr = new helical\requestr\router('action','subaction','pages');
	
// Output your template...
?>
<!doctype html>
<html>
<head><title>Requestr Example</title></head>
<body>
    <h1>Requestr Example</h1>
    <hr/>
    <?php
        // Output requestr and handle any errors:

        // $requestr->statusCode() != 200 executes the IF statement if we had a failure loading the script or class
        // !$requestr->run(); runs the page and executes the IF statement if it fails
        // $requestr->statusMessage() returns the error message should the IF execute for some reason

        if($requestr->statusCode() != 200 || !$requestr->run()){
            echo $requestr->statusMessage(); // You could put a 'error 404' template here if you want.
        }
    ?>
    <hr/>
    <p>The above text was generated by requestr</p>
    <p style="text-align:Center; font-size:12px; color:#333;">Requestr - Copyright (c) 2015 Russell Peterson &amp; Daniel Evans - <a href="http://helical.io">helical.io</a></p>
</body>
</html>